// Root application component — sets up routing and owns the shared draft-teams state.
//
// Draft teams data model:
//   allTeams = {
//     [leagueName]: {
//       [divisionName]: {
//         [teamKey]: { teamName, players, avg_experience }
//       }
//     }
//   }
//
// This nested map is generated by the Upload/GenerateTeams pages and flows down
// as props to Dashboard, GenerateTeams, and ScheduleManager. It is also persisted
// to the backend via /api/draft-teams so teams survive a page refresh (hydration
// runs on mount in the useEffect below). "Draft" means the teams are in the
// working/review stage — once an admin is happy they save them to the DB via
// the Dashboard, which creates ScheduledTeam records used by the Schedule Manager.
//
// The DashboardLayout component manages the mobile sidebar open/close state so
// every admin page gets the collapsible navigation without each page knowing about it.
import { useState, useEffect } from 'react'
import { BrowserRouter, Routes, Route, Navigate } from 'react-router-dom'
import { AuthProvider, getAuthToken, AUTH_HEADER_KEY } from './context/Authentication'
import ProtectedRoute from './components/ProtectedRoute'
import Dashboard from './pages/Dashboard'
import Upload from './pages/Upload'
import GenerateTeams from './pages/GenerateTeams'
import Settings from './pages/Settings'
import Login from './pages/Login'
import WebScraper from './pages/WebScraper'
import ScheduleManager from './pages/ScheduleManager'
import GameResultsManager from './pages/GameResultsManager'
import SeasonReset from './pages/SeasonReset'
import HomePage from './pages/HomePage'
import LeagueCalendarPage from './pages/LeagueCalendarPage'
import TeamPage from './pages/TeamPage'
import TeamsDirectory from './pages/TeamsDirectory'
import StandingsPage from './pages/StandingsPage'
import Sidebar from './components/Sidebar'
import SessionWarning from './components/SessionWarning'
import ErrorBoundary from './components/ErrorBoundary'

function DashboardLayout({ children }) {
  const [sidebarOpen, setSidebarOpen] = useState(false)

  return (
    <div className="flex min-h-screen bg-gray-900 text-white">
      {/* Mobile backdrop */}
      {sidebarOpen && (
        <div
          className="fixed inset-0 bg-black/50 z-30 md:hidden"
          onClick={() => setSidebarOpen(false)}
        />
      )}

      <Sidebar isOpen={sidebarOpen} onClose={() => setSidebarOpen(false)} />

      <div className="flex-1 min-w-0 flex flex-col">
        {/* Mobile top bar with hamburger */}
        <div className="md:hidden flex items-center gap-3 px-4 py-3 bg-[#0B1F3A] border-b border-gray-700 sticky top-0 z-20">
          <button
            onClick={() => setSidebarOpen(true)}
            className="text-white p-1.5 rounded hover:bg-white/10 transition"
            aria-label="Open menu"
          >
            <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
          <span className="text-red-500 font-bold text-sm tracking-wide">WEHA Admin</span>
        </div>

        <SessionWarning />
        <ErrorBoundary>
          <div className="flex-1 p-4 md:p-6">{children}</div>
        </ErrorBoundary>
      </div>
    </div>
  )
}

export default function App() {
  // Teams stored as:
  // { [leagueName]: { [divisionName]: { [teamKey]: teamData } } }
  const [allTeams, setAllTeams] = useState({})
  // true once the initial DB hydration fetch completes (success or failure)
  const [teamsLoaded, setTeamsLoaded] = useState(false)

  // On mount, pull any previously generated draft teams from the DB so the admin
  // doesn't lose their work if they refresh the page. We deep-merge: any teams
  // already in state (generated during this session before hydration finished)
  // take priority over the stored version to avoid overwriting in-session work.
  useEffect(() => {
    fetch('/api/draft-teams')
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then(data => {
        if (data && typeof data === 'object' && !data.error) {
          setAllTeams(prev => {
            // Deep-merge DB data under any keys not already present in current state.
            // Keys already in state (teams generated this session before hydration)
            // take priority so we never overwrite in-session work.
            const merged = { ...data }
            for (const [league, divMap] of Object.entries(prev)) {
              merged[league] = { ...(merged[league] || {}), ...divMap }
            }
            return merged
          })
        }
      })
      .catch(err => console.error('[draft-teams hydration failed]', err))
      .finally(() => setTeamsLoaded(true))
  }, [])

  // Called by Upload and GenerateTeams after a successful generate-teams API call.
  // Stores the new teams under league > division in allTeams and persists to DB.
  // The season suffix is stripped from divisionName so re-generating the same
  // division always overwrites the previous draft instead of creating a duplicate.
  const handleTeamsGenerated = (teamsData, divisionKey, leagueName, divisionName) => {
    // Strip any season-label suffix (e.g. "_unassigned (2024-2025)" → "_unassigned")
    // so that re-generating for the same league/division always replaces the previous
    // result rather than accumulating a new entry.
    const cleanDivName = divisionName.replace(/\s*\([^)]+\)$/, '').trim()
    setAllTeams(prev => ({
      ...prev,
      [leagueName]: {
        ...(prev[leagueName] || {}),
        [cleanDivName]: teamsData
      }
    }))
    // Persist to DB so teams survive a page refresh
    fetch('/api/draft-teams', {
      method:  'POST',
      headers: { 'Content-Type': 'application/json', [AUTH_HEADER_KEY]: getAuthToken() },
      body:    JSON.stringify({ leagueName, divisionName: cleanDivName, teamMap: teamsData }),
    }).then(r => { if (!r.ok) r.json().then(d => console.error('[draft-teams save failed]', d)) })
      .catch(err => console.error('[draft-teams save error]', err))
  }

  // Removes all draft teams for one division — used when the admin dismisses a
  // set of generated teams or wants to start over for that division.
  const handleDeleteDivision = (leagueName, divisionName) => {
    // Remove from DB
    fetch(`/api/draft-teams?leagueName=${encodeURIComponent(leagueName)}&divisionName=${encodeURIComponent(divisionName)}`, {
      method: 'DELETE', headers: { [AUTH_HEADER_KEY]: getAuthToken() },
    }).catch(() => {})
    // Remove from React state
    setAllTeams(prev => {
      const updatedLeague = { ...(prev[leagueName] || {}) }
      delete updatedLeague[divisionName]
      if (Object.keys(updatedLeague).length === 0) {
        const updated = { ...prev }
        delete updated[leagueName]
        return updated
      }
      return { ...prev, [leagueName]: updatedLeague }
    })
  }

  // Updates roster, name, or avg for one draft team after an in-Dashboard edit.
  // Persists the whole division's team map to DB so edits survive a refresh.
  const handleUpdateTeams = (leagueName, divisionName, teamKey, players, teamName, avg) => {
    setAllTeams(prev => {
      const updatedTeam = {
        ...(prev[leagueName]?.[divisionName]?.[teamKey] || {}),
        players,
        teamName,
        avg_experience: avg ?? prev[leagueName]?.[divisionName]?.[teamKey]?.avg_experience,
      }
      const updatedDiv = { ...(prev[leagueName]?.[divisionName] || {}), [teamKey]: updatedTeam }
      fetch('/api/draft-teams', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', [AUTH_HEADER_KEY]: getAuthToken() },
        body: JSON.stringify({ leagueName, divisionName, teamMap: updatedDiv }),
      }).catch(() => {})
      return { ...prev, [leagueName]: { ...(prev[leagueName] || {}), [divisionName]: updatedDiv } }
    })
  }

  // Moves one draft team across divisions within the same league. Used in the
  // Dashboard "Assign to division" flow for teams sitting in _unassigned.
  // Both the source and destination divisions are re-persisted; if the source
  // becomes empty it is deleted from the DB.
  const handleMoveTeam = (leagueName, fromDivision, toDivision, teamKey, teamData) => {
    setAllTeams(prev => {
      const league    = { ...(prev[leagueName] || {}) }
      const fromDiv   = { ...(league[fromDivision] || {}) }
      delete fromDiv[teamKey]
      const toDiv     = { ...(league[toDivision] || {}), [teamKey]: teamData }
      const updated   = { ...league, [fromDivision]: fromDiv, [toDivision]: toDiv }
      if (Object.keys(updated[fromDivision] || {}).length === 0) delete updated[fromDivision]

      // Persist the updated destination division to DraftTeam
      fetch('/api/draft-teams', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', [AUTH_HEADER_KEY]: getAuthToken() },
        body: JSON.stringify({ leagueName, divisionName: toDivision, teamMap: toDiv }),
      }).catch(() => {})

      // If fromDiv is now empty, remove it from DraftTeam; otherwise persist its new state
      if (Object.keys(fromDiv).length === 0) {
        fetch(`/api/draft-teams?leagueName=${encodeURIComponent(leagueName)}&divisionName=${encodeURIComponent(fromDivision)}`, {
          method: 'DELETE', headers: { [AUTH_HEADER_KEY]: getAuthToken() },
        }).catch(() => {})
      } else {
        fetch('/api/draft-teams', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json', [AUTH_HEADER_KEY]: getAuthToken() },
          body: JSON.stringify({ leagueName, divisionName: fromDivision, teamMap: fromDiv }),
        }).catch(() => {})
      }

      return { ...prev, [leagueName]: updated }
    })
  }

  // Deletes one individual draft team. If deleting it empties the division,
  // the division entry is also removed; if that empties the league, the league
  // entry is removed too — keeping allTeams clean of empty branches.
  const handleDeleteTeam = (leagueName, divisionName, teamKey) => {
    fetch(`/api/draft-teams?leagueName=${encodeURIComponent(leagueName)}&divisionName=${encodeURIComponent(divisionName)}&teamKey=${encodeURIComponent(teamKey)}`, {
      method: 'DELETE', headers: { [AUTH_HEADER_KEY]: getAuthToken() },
    }).catch(() => {})
    setAllTeams(prev => {
      const updatedDiv = { ...(prev[leagueName]?.[divisionName] || {}) }
      delete updatedDiv[teamKey]
      if (Object.keys(updatedDiv).length === 0) {
        const updatedLeague = { ...(prev[leagueName] || {}) }
        delete updatedLeague[divisionName]
        if (Object.keys(updatedLeague).length === 0) {
          const updated = { ...prev }
          delete updated[leagueName]
          return updated
        }
        return { ...prev, [leagueName]: updatedLeague }
      }
      return { ...prev, [leagueName]: { ...(prev[leagueName] || {}), [divisionName]: updatedDiv } }
    })
  }

  // Adds a brand-new empty draft team created manually in the Dashboard UI
  // (as opposed to generated by the algorithm).
  const handleAddTeam = (leagueName, divisionName, teamKey, teamData) => {
    setAllTeams(prev => {
      const updatedDiv = { ...(prev[leagueName]?.[divisionName] || {}), [teamKey]: teamData }
      fetch('/api/draft-teams', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', [AUTH_HEADER_KEY]: getAuthToken() },
        body: JSON.stringify({ leagueName, divisionName, teamMap: updatedDiv }),
      }).catch(() => {})
      return { ...prev, [leagueName]: { ...(prev[leagueName] || {}), [divisionName]: updatedDiv } }
    })
  }

  return (
    <AuthProvider>
      <BrowserRouter>
        <Routes>
          {/* Public routes */}
          <Route path="/" element={<HomePage />} />
          <Route path="/schedule" element={<LeagueCalendarPage />} />
          <Route path="/teams" element={<TeamsDirectory />} />
          <Route path="/standings" element={<StandingsPage />} />
          <Route path="/team/:teamID" element={<TeamPage />} />
          <Route path="/login" element={<Login />} />

          {/* Protected admin routes */}
          <Route path="/admin" element={
            <ProtectedRoute>
              <DashboardLayout>
                <Dashboard
                  allTeams={allTeams}
                  teamsLoaded={teamsLoaded}
                  onDeleteDivision={handleDeleteDivision}
                  onDeleteTeam={handleDeleteTeam}
                  onUpdateTeams={handleUpdateTeams}
                  onAddTeam={handleAddTeam}
                  onMoveTeam={handleMoveTeam}
                />
              </DashboardLayout>
            </ProtectedRoute>
          } />

          <Route path="/admin/upload" element={
            <ProtectedRoute>
              <DashboardLayout>
                <Upload onTeamsGenerated={handleTeamsGenerated} />
              </DashboardLayout>
            </ProtectedRoute>
          } />

          <Route path="/admin/generate-teams" element={
            <ProtectedRoute>
              <DashboardLayout>
                <GenerateTeams onTeamsGenerated={handleTeamsGenerated} />
              </DashboardLayout>
            </ProtectedRoute>
          } />

          <Route path="/admin/scraper" element={
            <ProtectedRoute><DashboardLayout><WebScraper /></DashboardLayout></ProtectedRoute>
          } />

          <Route path="/admin/schedule" element={
            <ProtectedRoute><DashboardLayout><ScheduleManager allTeams={allTeams} onDeleteDivision={handleDeleteDivision} /></DashboardLayout></ProtectedRoute>
          } />

          <Route path="/admin/settings" element={
            <ProtectedRoute><DashboardLayout><Settings /></DashboardLayout></ProtectedRoute>
          } />

          <Route path="/admin/game-results" element={
            <ProtectedRoute><DashboardLayout><GameResultsManager /></DashboardLayout></ProtectedRoute>
          } />

          <Route path="/admin/season-reset" element={
            <ProtectedRoute>
              <DashboardLayout>
                <SeasonReset onReset={() => setAllTeams({})} />
              </DashboardLayout>
            </ProtectedRoute>
          } />

          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </BrowserRouter>
    </AuthProvider>
  )
}
